# Simple GoReleaser configuration - just build binaries
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: walgo
    main: ./main.go
    binary: walgo
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # All OS + all architectures supported
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: walgo-archives
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

release:
  github:
    owner: selimozten
    name: walgo
  mode: keep-existing
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
  header: |
    ## Walgo {{ .Tag }}

    Installation:
    ```bash
    curl -fsSL https://raw.githubusercontent.com/selimozten/walgo/main/install.sh | bash
    ```