// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {main} from '../models';
import {ai} from '../models';

export function AICreateSite(arg1:api.AICreateSiteParams):Promise<void>;

export function ArchiveProject(arg1:number):Promise<api.ArchiveProjectResult>;

export function BuildSite(arg1:string):Promise<void>;

export function CheckDirectoryDepth(arg1:string):Promise<main.CheckDirectoryDepthResult>;

export function CheckSetupDeps():Promise<api.SetupDepsResult>;

export function CheckToolVersions():Promise<api.CheckToolVersionsResult>;

export function CleanAIConfig():Promise<void>;

export function CleanProviderConfig(arg1:string):Promise<void>;

export function Close():Promise<void>;

export function CopyFile(arg1:string,arg2:string):Promise<main.CopyFileResult>;

export function CreateAddress(arg1:string,arg2:string):Promise<api.CreateAddressResult>;

export function CreateDirectory(arg1:string):Promise<main.CreateDirectoryResult>;

export function CreateFile(arg1:string,arg2:string):Promise<main.CreateFileResult>;

export function DeleteFile(arg1:string):Promise<main.DeleteFileResult>;

export function DeleteProject(arg1:api.DeleteProjectParams):Promise<api.DeleteProjectResult>;

export function EditProject(arg1:api.EditProjectParams):Promise<api.EditProjectResult>;

export function EstimateGasFee(arg1:api.GasEstimateParams):Promise<api.GasEstimateResult>;

export function GenerateContent(arg1:api.GenerateContentParams):Promise<api.GenerateContentResult>;

export function GetAIConfig():Promise<api.AIConfigResult>;

export function GetAIProgress():Promise<main.AIProgressState>;

export function GetAddressList():Promise<api.AddressListResult>;

export function GetContentStructure(arg1:string):Promise<ai.ContentStructure>;

export function GetDefaultSitesDir():Promise<string>;

export function GetFolderStats(arg1:string):Promise<main.FolderStatsResult>;

export function GetInstalledThemes(arg1:string):Promise<api.GetInstalledThemesResult>;

export function GetProject(arg1:number):Promise<api.Project>;

export function GetProviderCredentials(arg1:string):Promise<api.ProviderCredentialsResult>;

export function GetServerURL():Promise<string>;

export function GetSystemHealth():Promise<api.SystemHealth>;

export function GetVersion():Promise<api.VersionResult>;

export function GetWalletInfo():Promise<api.WalletInfo>;

export function ImportAddress(arg1:api.ImportAddressParams):Promise<api.ImportAddressResult>;

export function ImportObsidian(arg1:api.ImportObsidianParams):Promise<api.ImportObsidianResult>;

export function InitSite(arg1:string,arg2:string):Promise<api.InitSiteResult>;

export function InstallTheme(arg1:api.InstallThemeParams):Promise<api.InstallThemeResult>;

export function LaunchWizard(arg1:api.LaunchWizardParams):Promise<api.LaunchWizardResult>;

export function ListFiles(arg1:string):Promise<main.ListFilesResult>;

export function ListProjects():Promise<Array<api.Project>>;

export function Maximize():Promise<void>;

export function Minimize():Promise<void>;

export function MoveFile(arg1:string,arg2:string):Promise<main.MoveFileResult>;

export function NewContent(arg1:api.NewContentParams):Promise<api.NewContentResult>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function OpenInFinder(arg1:string):Promise<void>;

export function ProjectNameExists(arg1:string):Promise<boolean>;

export function QuickStart(arg1:api.QuickStartParams):Promise<api.QuickStartResult>;

export function ReadFile(arg1:string):Promise<main.ReadFileResult>;

export function RemoveAICredentials(arg1:string):Promise<void>;

export function RenameFile(arg1:string,arg2:string):Promise<main.RenameFileResult>;

export function SelectDirectory(arg1:string):Promise<string>;

export function Serve(arg1:api.ServeParams):Promise<api.ServeResult>;

export function SetStatus(arg1:api.SetStatusParams):Promise<api.SetStatusResult>;

export function StopServe():Promise<boolean>;

export function SwitchAddress(arg1:string):Promise<api.SwitchAddressResult>;

export function SwitchNetwork(arg1:string):Promise<api.SwitchNetworkResult>;

export function UpdateAIConfig(arg1:api.AIConfigureParams):Promise<void>;

export function UpdateContent(arg1:api.UpdateContentParams):Promise<api.UpdateContentResult>;

export function UpdateSite(arg1:api.UpdateSiteParams):Promise<api.UpdateSiteResult>;

export function UpdateTools(arg1:api.UpdateToolsParams):Promise<api.UpdateToolsResult>;

export function WriteFile(arg1:string,arg2:string):Promise<main.WriteFileResult>;
