// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BuildSite(arg1:string):Promise<void>;

export function CreateSite(arg1:string,arg2:string):Promise<void>;

export function DeploySite(arg1:string,arg2:number):Promise<main.DeployResult>;
