// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AICreateSite(arg1) {
  return window['go']['main']['App']['AICreateSite'](arg1);
}

export function ArchiveProject(arg1) {
  return window['go']['main']['App']['ArchiveProject'](arg1);
}

export function BuildSite(arg1) {
  return window['go']['main']['App']['BuildSite'](arg1);
}

export function CheckSetupDeps() {
  return window['go']['main']['App']['CheckSetupDeps']();
}

export function CheckToolVersions() {
  return window['go']['main']['App']['CheckToolVersions']();
}

export function CleanAIConfig() {
  return window['go']['main']['App']['CleanAIConfig']();
}

export function CleanProviderConfig(arg1) {
  return window['go']['main']['App']['CleanProviderConfig'](arg1);
}

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function CreateAddress(arg1, arg2) {
  return window['go']['main']['App']['CreateAddress'](arg1, arg2);
}

export function CreateDirectory(arg1) {
  return window['go']['main']['App']['CreateDirectory'](arg1);
}

export function CreateFile(arg1, arg2) {
  return window['go']['main']['App']['CreateFile'](arg1, arg2);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function EditProject(arg1) {
  return window['go']['main']['App']['EditProject'](arg1);
}

export function EstimateGasFee(arg1) {
  return window['go']['main']['App']['EstimateGasFee'](arg1);
}

export function GenerateContent(arg1) {
  return window['go']['main']['App']['GenerateContent'](arg1);
}

export function GetAIConfig() {
  return window['go']['main']['App']['GetAIConfig']();
}

export function GetAddressList() {
  return window['go']['main']['App']['GetAddressList']();
}

export function GetContentStructure(arg1) {
  return window['go']['main']['App']['GetContentStructure'](arg1);
}

export function GetDefaultSitesDir() {
  return window['go']['main']['App']['GetDefaultSitesDir']();
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetProviderCredentials(arg1) {
  return window['go']['main']['App']['GetProviderCredentials'](arg1);
}

export function GetServerURL() {
  return window['go']['main']['App']['GetServerURL']();
}

export function GetSystemHealth() {
  return window['go']['main']['App']['GetSystemHealth']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWalletInfo() {
  return window['go']['main']['App']['GetWalletInfo']();
}

export function ImportAddress(arg1) {
  return window['go']['main']['App']['ImportAddress'](arg1);
}

export function ImportObsidian(arg1) {
  return window['go']['main']['App']['ImportObsidian'](arg1);
}

export function InitSite(arg1, arg2) {
  return window['go']['main']['App']['InitSite'](arg1, arg2);
}

export function LaunchWizard(arg1) {
  return window['go']['main']['App']['LaunchWizard'](arg1);
}

export function ListFiles(arg1) {
  return window['go']['main']['App']['ListFiles'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function Maximize() {
  return window['go']['main']['App']['Maximize']();
}

export function Minimize() {
  return window['go']['main']['App']['Minimize']();
}

export function NewContent(arg1) {
  return window['go']['main']['App']['NewContent'](arg1);
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}

export function OpenInFinder(arg1) {
  return window['go']['main']['App']['OpenInFinder'](arg1);
}

export function ProjectNameExists(arg1) {
  return window['go']['main']['App']['ProjectNameExists'](arg1);
}

export function QuickStart(arg1) {
  return window['go']['main']['App']['QuickStart'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RemoveAICredentials(arg1) {
  return window['go']['main']['App']['RemoveAICredentials'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function Serve(arg1) {
  return window['go']['main']['App']['Serve'](arg1);
}

export function SetStatus(arg1) {
  return window['go']['main']['App']['SetStatus'](arg1);
}

export function StopServe() {
  return window['go']['main']['App']['StopServe']();
}

export function SwitchAddress(arg1) {
  return window['go']['main']['App']['SwitchAddress'](arg1);
}

export function SwitchNetwork(arg1) {
  return window['go']['main']['App']['SwitchNetwork'](arg1);
}

export function UpdateAIConfig(arg1) {
  return window['go']['main']['App']['UpdateAIConfig'](arg1);
}

export function UpdateContent(arg1) {
  return window['go']['main']['App']['UpdateContent'](arg1);
}

export function UpdateTools(arg1) {
  return window['go']['main']['App']['UpdateTools'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
