// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {main} from '../models';

export function AICreateSite(arg1:api.AICreateSiteParams):Promise<api.AICreateSiteResult>;

export function ArchiveProject(arg1:number):Promise<api.ArchiveProjectResult>;

export function BuildSite(arg1:string):Promise<void>;

export function CheckSetupDeps():Promise<api.SetupDepsResult>;

export function CleanAIConfig():Promise<void>;

export function Close():Promise<void>;

export function CompressSite(arg1:string):Promise<void>;

export function ConfigureAI(arg1:api.AIConfigureParams):Promise<void>;

export function CreateSite(arg1:string,arg2:string):Promise<void>;

export function DeleteProject(arg1:number):Promise<void>;

export function DeploySite(arg1:string,arg2:number):Promise<main.DeployResult>;

export function Doctor():Promise<api.DoctorResult>;

export function EditProject(arg1:api.EditProjectParams):Promise<api.EditProjectResult>;

export function GenerateContent(arg1:main.GenerateContentParams):Promise<main.GenerateContentResult>;

export function GetAIConfig():Promise<api.AIConfigResult>;

export function GetAICredentials():Promise<api.AIConfigResult>;

export function GetProject(arg1:number):Promise<api.Project>;

export function GetServerURL():Promise<string>;

export function GetVersion():Promise<api.VersionResult>;

export function ImportObsidian(arg1:main.ImportObsidianParams):Promise<main.ImportObsidianResult>;

export function IsServing():Promise<boolean>;

export function LaunchWizard(arg1:api.LaunchWizardParams):Promise<api.LaunchWizardResult>;

export function ListProjects():Promise<Array<api.Project>>;

export function Maximize():Promise<void>;

export function Minimize():Promise<void>;

export function NewContent(arg1:api.NewContentParams):Promise<api.NewContentResult>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function OpenInEditor(arg1:string):Promise<void>;

export function OpenInFinder(arg1:string):Promise<void>;

export function OptimizeSite(arg1:string):Promise<void>;

export function QuickStart(arg1:api.QuickStartParams):Promise<api.QuickStartResult>;

export function RemoveAICredentials(arg1:string):Promise<void>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectFile(arg1:string,arg2:Array<string>):Promise<string>;

export function Serve(arg1:api.ServeParams):Promise<api.ServeResult>;

export function Status(arg1:string):Promise<api.StatusResult>;

export function StopServe():Promise<boolean>;

export function UpdateAIConfig(arg1:api.AIConfigureParams):Promise<void>;

export function UpdateContent(arg1:main.UpdateContentParams):Promise<main.UpdateContentResult>;

export function UpdateDeployment(arg1:api.UpdateDeploymentParams):Promise<api.UpdateDeploymentResult>;
