// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AICreateSite(arg1) {
  return window['go']['main']['App']['AICreateSite'](arg1);
}

export function ArchiveProject(arg1) {
  return window['go']['main']['App']['ArchiveProject'](arg1);
}

export function BuildSite(arg1) {
  return window['go']['main']['App']['BuildSite'](arg1);
}

export function CheckSetupDeps() {
  return window['go']['main']['App']['CheckSetupDeps']();
}

export function CleanAIConfig() {
  return window['go']['main']['App']['CleanAIConfig']();
}

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function CompressSite(arg1) {
  return window['go']['main']['App']['CompressSite'](arg1);
}

export function ConfigureAI(arg1) {
  return window['go']['main']['App']['ConfigureAI'](arg1);
}

export function CreateSite(arg1, arg2) {
  return window['go']['main']['App']['CreateSite'](arg1, arg2);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeploySite(arg1, arg2) {
  return window['go']['main']['App']['DeploySite'](arg1, arg2);
}

export function Doctor() {
  return window['go']['main']['App']['Doctor']();
}

export function EditProject(arg1) {
  return window['go']['main']['App']['EditProject'](arg1);
}

export function GenerateContent(arg1) {
  return window['go']['main']['App']['GenerateContent'](arg1);
}

export function GetAIConfig() {
  return window['go']['main']['App']['GetAIConfig']();
}

export function GetAICredentials() {
  return window['go']['main']['App']['GetAICredentials']();
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetServerURL() {
  return window['go']['main']['App']['GetServerURL']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportObsidian(arg1) {
  return window['go']['main']['App']['ImportObsidian'](arg1);
}

export function IsServing() {
  return window['go']['main']['App']['IsServing']();
}

export function LaunchWizard(arg1) {
  return window['go']['main']['App']['LaunchWizard'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function Maximize() {
  return window['go']['main']['App']['Maximize']();
}

export function Minimize() {
  return window['go']['main']['App']['Minimize']();
}

export function NewContent(arg1) {
  return window['go']['main']['App']['NewContent'](arg1);
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}

export function OpenInEditor(arg1) {
  return window['go']['main']['App']['OpenInEditor'](arg1);
}

export function OpenInFinder(arg1) {
  return window['go']['main']['App']['OpenInFinder'](arg1);
}

export function OptimizeSite(arg1) {
  return window['go']['main']['App']['OptimizeSite'](arg1);
}

export function QuickStart(arg1) {
  return window['go']['main']['App']['QuickStart'](arg1);
}

export function RemoveAICredentials(arg1) {
  return window['go']['main']['App']['RemoveAICredentials'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SelectFile(arg1, arg2) {
  return window['go']['main']['App']['SelectFile'](arg1, arg2);
}

export function Serve(arg1) {
  return window['go']['main']['App']['Serve'](arg1);
}

export function Status(arg1) {
  return window['go']['main']['App']['Status'](arg1);
}

export function StopServe() {
  return window['go']['main']['App']['StopServe']();
}

export function UpdateAIConfig(arg1) {
  return window['go']['main']['App']['UpdateAIConfig'](arg1);
}

export function UpdateContent(arg1) {
  return window['go']['main']['App']['UpdateContent'](arg1);
}

export function UpdateDeployment(arg1) {
  return window['go']['main']['App']['UpdateDeployment'](arg1);
}
