// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildSite(arg1) {
  return window['go']['main']['App']['BuildSite'](arg1);
}

export function CreateSite(arg1, arg2) {
  return window['go']['main']['App']['CreateSite'](arg1, arg2);
}

export function DeploySite(arg1, arg2) {
  return window['go']['main']['App']['DeploySite'](arg1, arg2);
}
